# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'NFCPassportReaderApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFCPassportReaderApp
  pod 'OpenSSL-Universal', :git => 'https://github.com/krzyzanowskim/OpenSSL.git', :branch => :master

end
