# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Disable use of input/output files here so that when we build it includes any changes to the development pod
# rather than having to manually clean and rebuuild each time
# Note this is commented out as it breaks archive project! But useful for dev
#install! 'cocoapods', :disable_input_output_paths => true

target 'NFCPassportReaderApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFCPassportReaderApp
  pod 'NFCPassportReader', :path => '../'
  pod 'QKMRZScanner'

  target 'NFCPassportReaderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

